### ISSUE TITLE
Consider determining stretch axis from the OpenType MATH table

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#106]
This is defined here https://w3c.github.io/mathml-core/#dfn-stretch-axis :

"The stretch axis of an embellished operator is inline if its core operator contains only text content made of a unique character c and that character has stretch axis inline per § B.2 Stretchy Operator Axis. Otherwise, stretch axis of the embellished operator is block."

This stretch axis makes much easier and understandable the stretch logic with embellished op & stretch size constraint ; I don't remember the details but there were some bugs in Firefox in the past because an embellished op hierarchy can contain both munderover & mrow expressions when we don't use that.

However, this currently adds a 492 bytes table ( after 6bb3e9eca3c06549339275aea3733817a18edc2a ). We could integrate into the operator dictionary, but it will probably reduce redundancy and make it bigger anyway.

A simple alternative would be to replace "if the stretch axis is inline/block" with "it is possible to stretchy glyph corresponding to c in the inline/block with the first available font".

Then this makes possible for operators like diagonal or "right angle" arrows to be stretchable in both inline and block directions depending on the context e.g. if the OpenType Table has both vertical/horizontal constructions. A single stretch axis (stretch size constrainst even) will continue to be determined by the container of the embellished operator and passed down to the core operator, so that there is no ambiguity on the stretch axis.

**Comment by davidcarlisle** [comment]
In principle (I don't comment on the implementation size details, you are better placed for that) I think it would be good to defer to the MATH table here, we might still want to have stretch information in unicode.xml and in (at least) mathml full as non normative information, just to set human expectations, but if a font doesn't implement an extendable character when the spec says it should  then it's not going to be a good outcome and conversely if a font implements additional extensions not foreseen by the current fixed list so the mathml system does not even attempt to stretch them, that could be a missed oportunity, So specifying that the stretch information (in either or both) directions comes from the MATH table of a suitable font would seem good to me.

**Comment by bkardell** [comment]
Discussed in 9/27/2021

Resolved that the core group believes this is a good simplification and are supportive of such a change.  Please open any follow up issue that is necessary.
