### ISSUE TITLE
Missing user-agent rule for semantics element

### ISSUE THREAD

**Issue by dginev** [w3c/mathml-core#107]
At the public working draft of MathML Core, specifically:
https://www.w3.org/TR/2021/WD-mathml-core-20210810/#semantics-example

There is an empty pre element which seems to be meant to hold a user-agent rule, as indicated by the text above:
> The user agent stylesheet must contain the following rule in order to only render the annotated MathML expression: 

```html
<pre data-include="user-agent-stylesheet/semantics.css" 
  data-include-id="include-49688684460505095"
  class="respec-offending-element" 
  title="`data-include` failed: `user-agent-stylesheet/semantics.css` (NetworkError when attempting to fetch resource.)." 
  id="respec-offender-data-include-failed-user-agent-stylesheet-semantics-css-networkerror-when-attempting-to-fetch-resource">
</pre>
```

Since I don't know how to patch that, opening an issue. I was reading through to check if MathML Core has a good prescription for browsers to cleverly recognize and ignore the annotation children of a `<semantics>` element, while still keeping them available for other applications (frontend apps, clipboards, AT)

**Comment by fred-wang** [comment]
I see it in the draft: https://w3c.github.io/mathml-core/#semantics-and-presentation

**Comment by dginev** [comment]
I see it at @fred-wang 's link as well, could be a deployment problem

**Comment by bert-github** [comment]
It seems all the external data linked with ‘data-include’ attributes failed to get included. I guess that is my fault: I should have checked that the output from ReSpec didn't contain any errors, before publishing the document.

Luckily, publishing an update should be pretty quick and easy.

An agenda item for the next telcon?

**Comment by davidcarlisle** [comment]
Thi shas been fixed at source and re-published
