### ISSUE TITLE
Summation should start at 1

### ISSUE THREAD

**Issue by davidfarmer** [w3c/mathml-core#110]
The example used in Section 2.1.1 https://www.w3.org/TR/2021/WD-mathml-core-20210816/#the-top-level-math-element
is supposed to be (in TeX notation)

`\sum_{n=1}^{+\infty} \frac{1}{n^2} = \frac{\pi^2}{6}`

However, in the given mathml markup, and in two images, the summation starts at 0,
not at 1 as I show above.

The same error is repeated in Section 2.2.2, once in mathml markup and once in an image.
(Also, the summation sign in that image looks too small.)

I cloned the repository to try and fix this, but it was mysterious to me how to do things
like generate the images.

**Comment by davidcarlisle** [comment]
Thanks. should be fixed now in the respec source at https://w3c.github.io/mathml-core/#css-styling so will be fixed in teh next draft in /TR

**Comment by davidfarmer** [comment]
I don't see the change in the second image in 2.1.1, showing the inline 
case.

**Comment by davidcarlisle** [comment]
sorry, missed one
