### ISSUE TITLE
Bracket Pairs

### ISSUE THREAD

**Issue by stefnotch** [w3c/mathml-core#112]
While building a prototype of a math editor, I realized that bracket-pairings are important. For instance, if one has a large sum symbol, the the preference is usually to have large brackets. 
So, if the user types `(1+[2,3]` and then types `)`, it's reasonable that the `)` should be paired with the `(`. Of course it's a heuristic that can fail, especially once someone starts using [absolute value bars `| |` in the set-builder notation](https://wikimedia.org/api/rest_v1/media/math/render/svg/e092f38e7fcabebc72f44fce0ffa388b5decba5c).

But anyways, I was looking through the [MathML Core operator dictionary](https://www.w3.org/TR/mathml-core/#operator-dictionary), searching for a reasonably clear *"this opening bracket corresponds to that closing bracket"* text in the spec. I haven't found anything, however there does seem to be that pattern in the table. Can that be relied on? Or is it just a happy coincidence?

![image](https://user-images.githubusercontent.com/10220080/147860815-f3df9d87-9d7b-4516-86dc-155a65434af8.png)

**Comment by NSoiffer** [comment]
If you are referring to opening delimiters being listed as prefix and closing ones listed as postfix, then yes you can rely on that.

Note that some such as "|" can be _both_ prefix and postfix.

Also, don't forget about interval notation where "(0, 1]" is meaningful or the "cases" notation which has a large left brace but no matching brace.

**Comment by stefnotch** [comment]
Lovely, thank you for the answer. Is there also a way of figuring out that, say `{` will be closed by `}`? And `|` should be closed by `|`?
So, if the user types `{a|b}`, it's clear that the `{` and `}` belong to each other, and that `|` doesn't have a closing one?

Yes, the interval notation is a special case. I think I'll make my parser extensible enough to theoretically support it, but won't actually add support for that cursed notation by default.

**Comment by NSoiffer** [comment]
Vertical bars are particularly tricky as they can be prefix, infix, and postfix. Even when used for absolute value, decisions need to be made. E.g, how does `|a|b|c|` group?

The operator dictionary can't help you out on deciding what matches with what. If you want to keep track of "normal" pairings such as `()` and `[]`, you'll need to build your own table.

**Comment by stefnotch** [comment]
> Vertical bars are particularly tricky as they can be prefix, infix, and postfix. Even when used for absolute value, decisions need to be made. E.g, how does `|a|b|c|` group?

Yes, definitely. My hope is that I can leave this up to the user at editing time. Everything else seems like a fun guessing game.
- when the user types a `|`, I automatically insert a second, grayed out `|`. (abs) 
- if they type a second `|`, the bars get replaced with `‖`. (norm)
- and if they hit `esc` or delete the second, grayed out `|`, they clearly don't want an absolute value

> The operator dictionary can't help you out on deciding what matches with what. If you want to keep track of "normal" pairings such as `()` and `[]`, you'll need to build your own table.

Sounds good, I'll build my own table then.

**Comment by stefnotch** [comment]
For the record, here is my table
```js
const bracketsList = [
  ["(", ")"], // U+0028, U+0029
  ["[", "]"], // U+005B, U+005D
  ["{", "}"], // U+007B, U+007D
  ["⌈", "⌉"], // U+2308, U+2309
  ["⌊", "⌋"], // U+230A, U+230B
  ["〈", "〉"], // U+2329, U+232A
  ["❲", "❳"], // U+2772, U+2773
  ["⟦", "⟧"], // U+27E6, U+27E7
  ["⟨", "⟩"], // U+27E8, U+27E9
  ["⟪", "⟫"], // U+27EA, U+27EB
  ["⟬", "⟭"], // U+27EC, U+27ED
  ["⟮", "⟯"], // U+27EE, U+27EF
  ["⦃", "⦄"], // U+2983, U+2984
  ["⦅", "⦆"], // U+2985, U+2986
  ["⦇", "⦈"], // U+2987, U+2988
  ["⦉", "⦊"], // U+2989, U+298A
  ["⦋", "⦌"], // U+298B, U+298C
  ["⦍", "⦎"], // U+298D, U+298E
  ["⦏", "⦐"], // U+298F, U+2990
  ["⦑", "⦒"], // U+2991, U+2992
  ["⦓", "⦔"], // U+2993, U+2994
  ["⦕", "⦖"], // U+2995, U+2996
  ["⦗", "⦘"], // U+2997, U+2998
  ["⧘", "⧙"], // U+29D8, U+29D9
  ["⧚", "⧛"], // U+29DA, U+29DB
  ["⧼", "⧽"], // U+29FC, U+29FD
];
const ambigousBracketsList = [
  ["|", "|"], // U+007C, U+007C
  ["‖", "‖"], // U+2016, U+2016
  ["⦀", "⦀"], // U+2980, U+2980
  ["⦙", "⦙"], // U+2999, U+2999
];
```

**Comment by dginev** [comment]
A bit of an evangelizing comment from me, but I think needed context for future readers of the issue:

@stefnotch the set of constructs which can act as "balanced fences" (what you are calling "bracket pairs") is open, and authors keep innovating on the theme, especially in research texts. Here is an example from arXiv:1710.06709 related to Fourier series:

<img src="https://user-images.githubusercontent.com/348975/148299821-a06c43d1-cae0-4a23-a08f-d51421cfc29c.png" width=512>

Not to say you should be supporting these in your software, just making it explicit there is a lot of possible variation in existing texts.

**Comment by stefnotch** [comment]
That's a really interesting notation, thank you for bringing this to my attention! I never considered the possibility of balanced fences being more than one symbol on either side. This is nice and most certainly worth considering for my software. Time to change the data structure to allow for entire sub-trees for brackets. ;)

Also, regarding the auto-sizing feature of brackets, I can't get such brackets to auto-size when doing it with LaTeX. It's quite likely that I'm just typesetting them wrong.
```latex
\overset{\wedge}{ \Big( \hspace{-4px} \Big(} \frac{1}{2} + 3 \overset{\wedge}{\Big) \hspace{-4px} \Big)}
```

![image](https://user-images.githubusercontent.com/10220080/148459748-0e658ce3-8c36-47cc-ba3b-2fc95bdfe090.png)

However, MathML is perfectly happy with auto-sizing brackets that have extra symbols above them? If that's actually true and is reliable, then that's amazing!
```mathml
<math xmlns="http://www.w3.org/1998/Math/MathML">
    <mo>∑</mo>
    <mrow>
    <mo>(</mo><mn>0</mn><mo>)</mo>
    </mrow>
<mrow>
  <mover><mo>(</mo> <mi>1</mi></mover>
  <mrow> <mfrac> <msqrt><mi>b</mi><mi>x</mi></msqrt> <mpadded height="1em" ><mn>2</mn></mpadded> </mfrac> </mrow>
  <mover><mo>)</mo> <mi>1</mi></mover>
  </mrow>
</math>
```
![image](https://user-images.githubusercontent.com/10220080/148460658-efa37581-9e7d-46b1-baee-f8745a31e026.png)

**Comment by NSoiffer** [comment]
Yes, MathML will _by default_ (can be overwritten) cause stretchy chars to stretch to the size of the largest element in their containing `mrow`.

**Comment by brucemiller** [comment]
>, I can't get such 
> brackets to auto-size when doing it with LaTeX. It's quite likely that 

Use $\left( bigstuff \right)$.

**Comment by davidcarlisle** [comment]
@brucemiller  these are double brackets annotated with a hat accent: I  think luatex could handle that natively except I couldn't find a math font with an extendable U+2E28 ⸨
