### ISSUE TITLE
intent attribute

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml-core#115]
MathML4 will specify  `intent` and `arg`  attributes to provide some control over accessibility mappings.

MathML Core should specify that these attributes are a valid attribute, probably in [Global attributes](https://w3c.github.io/mathml-core/#global-attributes), even if it has no specified behaviour at this level.

**Comment by NSoiffer** [comment]
Although not discussed much, there is a chance that a `subject` attribute will added also. I think the same treatment should be given.

**Comment by dginev** [comment]
> Although not discussed much, there is a chance that a `subject` attribute will added also. I think the same treatment should be given.

I'd really like us to discuss this to a point where it's useful, before we make the provisions of adding an attribute though. I'm still not sure subject areas are a clearcut+useful technical component.

As we've seen with `intent` and `arg`, due diligence takes a bit of time.

**Comment by NSoiffer** [comment]
In #150, `intent` was mentioned tangentially along with `alt-text`.

I'd really like to think  `alt-text` is not needed these days, but unfortunately, it seems like it might be too early to deprecate it. The importance of mentioning `intent`, `arg`, and likely `alt-text` in core is that they need to go into the accessibility tree.

The spec is currently silent on accessibility which probably means it won't get past APA's review. Adding an appendix on accessibility of MathML and what should be part of the accessibility tree is probably not just a good idea, it will probably be a requirement.

If there are no objections to adding an accessibility appendix (there will be one in MathML Full), I'll write some strawman text.

**Comment by NSoiffer** [comment]
`intent` and `arg` were added to the core spec. `subject` is not needed as we have embedded a property syntax inside `intent` in MathML 4.

Closing this issue.
