### ISSUE TITLE
MathML-Core meeting, Monday March 28, 2022 Agenda 

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#118]
Agenda items, feel free to reply to suggest more.

* Brief progress updates/plans?
   * minutes issues / agenda+
   * quick check in on stable and compact operator dictionary #104 :  https://github.com/w3c/mathml-core/issues/104 

* Intent attribute #115 : https://github.com/w3c/mathml-core/issues/115 
* Decide how to handle unknown MathML Elements #71 : https://github.com/w3c/mathml-core/issues/71

**Comment by davidcarlisle** [comment]
If we get to discuss intent attribute #115 we might also consider allowing alttext. Core wouldn't need to specify any behaviour for alltext, as it's for implementations that don't implement core, but we should probably decare it valid.

w3c pubrules for example states

https://www.w3.org/pubrules/doc/rules/?profile=REC#format

> Inline markup for MathML is permitted but should use a (fallback) alternative.

which isn't entirely clear but I think means you need to use alttext or altimage.

We could of course get pubrules changed, but the basic requirement of providing something for systems that don't support the math markup won't go away.

**Comment by davidcarlisle** [comment]
New Core issue just posted #119
