### ISSUE TITLE
https://w3c.github.io/mathml-core/ not displaying the latest spec

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#144]
https://w3c.github.io/mathml-core/ is showing the initial "Straw Man MathML Web Profile" spec to me, not the latest version of the spec this morning. But I don't see any commit since Mar 21.

**Comment by davidcarlisle** [comment]
sorry, accidental trip down memory lane (fixed, no change to repo, just setting the right branch again in the github UI)

**Comment by fred-wang** [comment]
Thanks!
