### ISSUE TITLE
Semantic deficiencies in the MathML 3 specification.

### ISSUE THREAD

**Issue by MicuentaGit** [w3c/mathml-core#147]
After having read your MathML Core specification, I think I can make contributions that may interest you.

If a computational language must have a requirement, it is that what is expressed with it lacks ambiguities, since computers are not like humans who can obtain meaning from context. In this sense, there is a glaring error in the specification in not distinguishing between a superscript and raising to a power. But unfortunately, it is not the only error:
The notation of a number with a fractional part varies depending on the country, being the comma or the period the separator between the fractional part and the integer. In my case, I prefer the apostrophe as the separator to avoid ambiguity, and this allows me to use the period as a thousand separator. Therefore, there must be a way in the language to express the chosen notation.
If the fractional part of the number has a periodic part, there is no way to notice it with the specification, and the authors need to repeat the periodic part and add an ellipsis to signal the period.
There are many more different ways to represent an integer than using the decimal base. For example, in the field of programming, an integer may appear in binary or hexadecimal format, or another way to represent a number is using Roman numerals.
Furthermore, letters identify irrational numbers because it is impossible to identify them with decimal characters. Because of the use of letters, authors can get confused and treat them as if they were variable names by using the tag <mi> instead of the tag <mn>. Examples of these irrational numbers are pi, Euler number, Euler-Mascheroni constant, Champernowne number, …
Even the meaning of the operator depends on the context. We are expected to express them with the commonly used symbol, but that symbol represents different meanings depending on the context. For example, a scalar product of two vectors is not the same as the product of two scalar numbers; in the first case, it returns a number instead of a vector, while in the second case the result is of the same type as its operands. Since the specification has not a way of identifying the type of operands of the operator, it is impossible to get the meaning of the operator without knowing the context.

In addition to these ambiguities, the specification makes use of tags contrary to the definition given. Parentheses and brackets are not operators, but delimiters. The specification uses the <mrow> tag to group algebraic expressions, but when the grouping is explicit with delimitations, the specification asks to use <mo> to indicate the delimiter. Delimiters are not operators, and <mo> tags claim to enclose an operator.

To ignore these shortcomings is to go against the philosophy of HTML. It makes no sense for the author to risk a bug in the rendering engine displaying the mathematical expression incorrectly if in return he has not had the opportunity to express precisely what he is referring to. The competent author will prefer the security of an SVG.

It should also be considered that a larger vocabulary than already enumerated in the specification will be needed in the future. Therefore, the current vocabulary must be such that it allows incorporating the new vocabulary without having to redefine the existing one. Furthermore, the current vocabulary will have forced authors to write expressions using an arbitrary formulation, for which the specification lacks a description of its formulation, and will cause the requirement of human intervention in an updated reformulation.

For example, we have defined the function of the nth root and, however, we do not have the possibility of expressing any trigonometric function. A label can be defined to express that we mean a function; the element would have one attribute to give its normalized name and another to give the number of arguments; the element's descendants could be a single <mi> child for the author to express the name of the function chosen to appear in the mathematical expression and as many argument's tags as arguments has the function; the descendants of the argument labels would be the algebraic expressions; and the author would choose how to delimit arguments from the rest of expression and to separate them from each other.

I don't think it's useful that browsers gives support to ambiguous mathematical expressions when browsers withdraw its support to them until now. I think this specification should define a new namespace to be able to make modifications to the definitions of the current vocabulary it uses. The browser support given to the current vocabulary should be a best-effort treatment without any warranty of being correctly well rendered.

**Comment by dginev** [comment]
@MicuentaGit what you refer to as a "computational language" falls closer to the Content MathML branch of MathML, which is distinct and separate from MathML Core. To quote from MathML Core's introduction:

> This MathML Core specification intends to address these issues by being as accurate as possible on the visual rendering of mathematical formulas

For the current iteration of MathML work, we have internally decided to "freeze" Content MathML to its state in version 3, but you will indeed find a distinct `<power>` element there.

If you think the two branches should be combined into a single unambiguous tree that solves both questions (rendering + computation) together, you are faced with a very hard question -- should MathML generators be unable to generate *any* MathML from natural language mathematics texts, where we indeed write superscripts and subscripts, rather than powers or indexes. Texts are meant to communicate information between human beings, rather than symbolic systems, so requiring their expressions to be unambiguously computable goes beyond their primary function.

I personally find this to be an impossible requirement, but a very reasonable *optional capability*, which can be discussed further for MathML 5, when the Content branch will not be "frozen" by our charter. I would welcome you to join us in these discussions!

As to:
> I don't think it's useful that browsers gives support to ambiguous mathematical expressions when browsers withdraw its support to them until now. 

This statement is more tech-politics than objectively informed I'm afraid. Here is another political statement of equal and opposite force: 

You will find billions of MathML 3 expressions on the open web today, and all major browsers either have MathML support enabled, or are currently actively working on enabling it in the short term.

**Comment by davidcarlisle** [comment]
Thank you for your comments but I think you misundersand the intent of MahML Core, which is to specify the rendering of MathML in a web platform browser. Other vocabularies such as Content MathML [1] or OpenMath [2] are designed to hold enough mathematical meaning to be used with computational Math Engines.

As a rendering vocabulary it can be compared wih TeX (or SVG which you mention) which would similarly not try to encode unambiguous mathematical meaning.


[1] https://w3c.github.io/mathml/#contm

[2] https://openmath.org/

**Comment by davidfarmer** [comment]
Recent discussions have focused on disambiguating notation for
the purpose of enabling correct pronunciation.  This involves
distinguishing between superscript as power, and superscript
as exponent, for example.  An "intent" attribute would be used
to provide that information.

The details have not been finalized.

**Comment by MicuentaGit** [comment]
> @MicuentaGit what you refer to as a "computational language" falls closer to the [Content MathML](https://www.w3.org/TR/MathML/chapter4.html#contm.intro) branch of MathML, which is distinct and separate from MathML Core. To quote from MathML Core's introduction:

@dginev: In my opinion, content MathML should be an attempt to express mathematics without making use of notational rules; for example, a number must have a unique representation and, therefore, there would be no place in this language to indicate if the number is in a decimal or hexadecimal base.
Any computational language, regardless of its purpose, must avoid having ambiguities.

**Comment by MicuentaGit** [comment]
> As a rendering vocabulary it can be compared with TeX (or SVG which you mention) which would similarly not try to > encode unambiguous mathematical meaning.

@davidcarlisle: In my opinion, HTML is not a rendering language, its intention is that the author can express the meaning of what he is including in the document written in this language. For example, <p> means paragraph and can have different renderings depending on your choice in the CSS.

**Comment by MicuentaGit** [comment]
For example, `<p>` means paragraph and can have different renderings depending on your choice in the CSS.

(Sorry, I miss escaping the term.)

**Comment by MicuentaGit** [comment]
Some corrections on my first post:
…by using the tag `<mi>` instead of the tag `<mn>`.

The specification uses the tag `<mrow>` to group algebraic expressions…the specification asks to use `<mo>` to indicate the delimiter.  …and `<mo>` tags claim to enclose an operator.

(I apologize for the inconvenience of my errors.)

**Comment by dginev** [comment]
> @dginev: In my opinion, content MathML should be an attempt to express mathematics without making use of notational rules;

Great, as that is exactly what it is. Elements in Content MathML do not have a prescribed mandatory notation.

Our group participants have broad consensus that there is a "many-to-many" relationship between notations and concepts. We have plenty of examples where the same syntax could stand for two or more meanings, and the same meaning could be written down in two or more syntactic forms.

> for example, a number must have a unique representation and, therefore, there would be no place in this language to indicate if the number is in a decimal or hexadecimal base. 

This is a bit misplaced, as no symbolic number exists independent of base. A symbolic number *has* a base or the adjacency of digits conveys no information. At best, one could standardize an implied default base (which [non-strict use of cn](https://www.w3.org/TR/MathML3/chapter4.html#contm.cn.extended) has done, it is base 10). 

Making other bases impossible to write down in MathML doesn't solve a problem as much as it delegates it to spec adopters, and incurs a runtime penalty, as they would have to convert to/from base 10 whenever their intended bases differ.

> Any computational language, regardless of its purpose, must avoid having ambiguities.

I certainly agree with the general sentiment, but would insist that this depends *tightly* on applications.

Also, specifying a `base` attribute has exactly the function of avoiding ambiguity. I would suspect you will find the current Content MathML dialect quite compatible with your foundational expectations in this regard. 

What Content MathML can still benefit from are improved ergonomics, more out-of-the-box interop with the vocabularies of mainstream systems and a more transparent set of practices for enabling the very diverse set of applications that require a standard interchange format for mathematical expressions. 

I wouldn't say there are "semantic deficiencies" in the way MathML Core or Content MathML were written, as a general statement. So I'd offer to close this issue while again inviting you to join us on the [mailing list](https://lists.w3.org/Archives/Public/www-math/) for further discussions, maybe in the concrete applications of MathML that you find valuable.

**Comment by MicuentaGit** [comment]
> Our group participants have broad consensus that there is a "many-to-many" relationship between notations and
> concepts. We have plenty of examples where the same syntax could stand for two or more meanings, and the
> same meaning could be written down in two or more syntactic forms.

And because HTML is meant to express meaning rather than just describe a rendering, we need to be able to express more information than simply describing the graphical representation.

> Making other bases impossible to write down in MathML doesn't solve a problem as much as it delegates it to
> spec adopters, and incurs a runtime penalty, as they would have to convert to/from base 10 whenever their
> intended bases differ.

I do not mean that the browser should do any conversion. If the number appears in hexadecimal it is not for the browser to transform it into decimal, the author wants to express that number that way. However, the browser will not understand that AB is a number if no information is included.

Content MathML should only have one representation for each meaning in its language, and presentation MathML should cover all possible representations of the same meaning and assure that the exact meaning of the representation can be expressed on it.

**Comment by davidfarmer** [comment]
Closing, because the www-math mailing list is the appropriate place to continue
these discussions (probably split into separate topics because there are multiple issues).

**Comment by MicuentaGit** [comment]
> Closing, because the www-math mailing list is the appropriate place to continue
> these discussions (probably split into separate topics because there are multiple issues).

I hate to say this, I don't agree with the decision and the argument given seems ridiculous to me. I was going to report another issue, but I'm not going to make the effort to expose it after this decision.
Cheers.
