### ISSUE TITLE
Be more explicit about anonymous mrow boxes

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#152]
The `<mrow>` element is a generic grouping element, performing layout of children in a row with additional features such as vertical stretching or automatic spacing of operators.

MathML3 used the concept of [inferred mrow](https://www.w3.org/TR/MathML3/chapter3.html#presm.inferredmrow) to allow any number of children inside elements that conceptually accept a single argument. However, the "is treated as if there was an `<mrow>`" is a bit ambiguous there are many things (e.g. CSS selectors or DOM operations) that don't apply the same with or without an explicit `<mrow>`. Consequently, MathML Core does not mention that at all and instead just says how to layout boxes to get the expected result.

When implementing this in Chromium, we ended up using [anonymous boxes](https://andreubotella.com/csswg-auto-build/css2/#anonymous-block-level) in two cases: `<msqrt>` or `<mtd>`. This concept is familiar to browser implementors and being explicit would facilitate implementations and avoid inconsistencies between them. I'm going to upload a PR doing that.

Browsers generally distinguish between the element tree and the box tree, but we don't really do that in the mathml core spec. In particular, embellished operators and space-like elements are concepts that apply to the element tree, but really Chromium relies on the box tree instead. Changing the definition will likely be a bit tricky so for now I'm just adding notes explaining how to apply these definition for boxes.

**Comment by NSoiffer** [comment]
In MathML3, the following elements have inferred mrows: `msqrt`, `mstyle`, `merror`, `mpadded`, `mphantom`, `menclose` (not in core), `mtd`, `math`, and `mscarry` (not in core).

Most of these have the same layout algorithm as `mrow`, so I can see that maybe they don't cause problems. Of the remaining ones that are in core, you mentioned `msqrt` and `mtd`. `mpadded` does not use the mrow layout algorithm, so shouldn't it use anonymous boxes also?

**Comment by fred-wang** [comment]
@NSoiffer Right, mpadded uses anonymous boxes too.

Chromium's implementation:
https://source.chromium.org/search?q=LayoutNGTableCellWithAnonymousMrow%7CLayoutNGMathMLBlockWithAnonymousMrow&sq=

**Comment by fred-wang** [comment]
OK I checked again and PR https://github.com/w3c/mathml-core/pull/153 was actually already handling the mpadded element. However, it was missing the `mtd` case so I fixed that.

**Comment by bkardell** [comment]
Closing as we merged #153
