### ISSUE TITLE
Regenerate PNG examples with official chromium build

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#155]
In the past screenshots were generated from Igalia's `chromium-mathml` build. Recently, I regenerated screenshots with Chromium 102 or with a trunk build. I guess at some point if would be good to run the script again with a fixed version of Chromium, probably when MathMLCore is enabled by default.

However, there will be known issue with the initial MathML release in Chromium. Especially, contrary to Igalia's `chromium-mathml` it won't follow exactly the MathML Core spec regarding stretchy operators ( see https://mathml.igalia.com/project/#width-of-stretchy-operators-blocked-on-chromiums-refactoring ) leading to extra gaps in formulas.

I gave a try at https://github.com/fred-wang/mathml-core/commit/09ef6c37fa1da1e032c896620c4ce9a74128ca60 and the issue is particularly visible for msqrt/mroot ( I opened https://bugs.chromium.org/p/chromium/issues/detail?id=1339724 for this one).

**Comment by davidcarlisle** [comment]
Decided to take no action now, closing
