### ISSUE TITLE
Typo re: symmetric

### ISSUE THREAD

**Issue by ronkok** [w3c/mathml-core#161]
Following MathML Core section 3.2.4, there are a couple of examples. In the example text is the sentence "The [symmetric](https://w3c.github.io/mathml-core/#dfn-symmetric) attribute allows to indicate whether the operator should stretch symmetrically above and below the baseline."

I believe that last word is a typo. It should indicate symmetry above and below the math axis.

**Comment by fred-wang** [comment]
Correct that should be above and below the math axis. Probably the example should be tweaked a bit (e.g. add a fraction before the symmetric operator) so it's easier to see where the math axis is located.
