### ISSUE TITLE
empty element test is wrong

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml-core#163]
The resolution of w3c/mathml-core#136 means that the test/code in `presentation-markup/scripts/empty-underover.html` is wrong. Those tests assume that having no children means the element takes 0 space. Given that these elements retain their layout based on w3c/mathml-core#136 resolution, there are some min gaps and shifts that cause the elements to have some size (true for msub, munder, etc.)

**Comment by fred-wang** [comment]
This can be closed. https://wpt.fyi/results/mathml/presentation-markup/scripts/empty-underover.html pass in all browsers:

- Firefox 106 and Chrome 109 follows the spec and perform layout as an mrow with empty scripts.
- WebKit perform layout as an empty box.
