### ISSUE TITLE
MathML Core Meeting Sept 26, 2022

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#168]
Agenda items, feel free to reply to suggest more.  Unless someone has specific issues they'd like to add, I'd like to suggest that we use this session a little more organizationally about moving forward than to discuss details of specific issues.

* Brief progress updates/plans?
   * display: ...?
   * [Interop 2023](https://github.com/web-platform-tests/interop/issues/147)
* Let's collect a vote to move to CR. Discussing at TPAC, @NSoiffer and I believe we are ready to do that..
* Early scoping for L2?

**Comment by NSoiffer** [comment]
Possibly discuss Operator dictionary: [Order of preference for forms #167](https://github.com/w3c/mathml-core/issues/167)
