### ISSUE TITLE
Operator Dictionary specification has lspace,rspace switched.

### ISSUE THREAD

**Issue by brucemiller** [w3c/mathml-core#174]
It would appear that the column headings for `lspace`, `rspace` are switched in Figure 26 in the Operator Dictionary section.  Category M, which includes "," calls for spacing on the left, rather than on the right.

**Comment by davidcarlisle** [comment]
Seems that way,  thanks. @fred-wang  can we just editorially swap the headings or has this found its way in to code that needs correcting?

**Comment by fred-wang** [comment]
will check, but will likely need to edit the python script

**Comment by dginev** [comment]
> editorially swap the headings or has this found its way in to code that needs correcting?

A very minor comment on my part that agrees with David for reasons of "intuitive reading":

It will be helpful for unsuspecting readers if the column describing the "left" spacing was positioned on the left of the column describing the "right" spacing. Silly point I know, but the counter-intuitive positioning could become a source of unfortunate copy-pasting mishaps.

**Comment by fred-wang** [comment]
Yes, so checking `tables/operator-dictionary.py`, the function `serializeValue` serializes spacing in the order lspace, rspace but `operator-dictionary-table` and `operator-dictionary-table` have their headers in the order rspace, lspace. I'll fix that.

**Comment by fred-wang** [comment]
Done, thanks for the report.
