### ISSUE TITLE
Unexport definitions for the html global attributes

### ISSUE THREAD

**Issue by tabatkins** [w3c/mathml-core#186]
Currently, mathml-core contains `<dfn>`s for the HTML global attributes (id, dir, etc). These are just deferring to the HTML definitions (with the exception of `dir` which has some additional processing rules).

This causes a link conflict for any spec trying to refer to those attributes, requiring the spec author to disambiguate. As far as I can tell, however, there is no need for any spec outside of mathml-core to link to these definitions; they're not intended for global consumption.

Could you mark them as `no-export`? That would fix the problem for outside specs, and still allow for specs to link directly to mathml-core's versions of the definition if they for some reason found that necessary.

(For now, I'm going to mark the HTML versions as superceding the MathML versions in Bikeshed, but I prefer keeping the special-case exceptions to a minimum.)

**Comment by davidcarlisle** [comment]
er yes I guess we'll clear up, I'll ping here when I think it's done for you to confirm

**Comment by davidcarlisle** [comment]
@tabatkins  respec documents `export` but not `no-export` but I see it in the code.

https://respec.org/docs/#data-export

 Can you confirm [11f8b36](https://github.com/w3c/mathml-core/commit/11f8b364eefb43221cb85450dddf13713c7bf310) is what you meant?

**Comment by tabatkins** [comment]
I'm not familiar with ReSpec internals, but if you're seeing it in the ReSpec code, then yeah.

Assuming that `class=no-export` is indeed the opposite of `class=export`, then that fix is :+1:

**Comment by bkardell** [comment]
@tabatkins we think this is fixed, please reopen if we're wrong
