### ISSUE TITLE
Incorrect reflect usage

### ISSUE THREAD

**Issue by annevk** [w3c/mathml-core#188]
> Each IDL attribute of the [MathMLElement](https://w3c.github.io/mathml-core/#dom-mathmlelement) interface reflects the corresponding MathML [content attribute](https://w3c.github.io/mathml-core/#global-attributes).

All these attributes are already defined in HTML and many of them don't even use "reflect" underneath. You shouldn't need this definition for things to work.

**Comment by fred-wang** [comment]
cc @bkardell

**Comment by bkardell** [comment]
closed by 197 / wg resolution
