### ISSUE TITLE
Usage of HTML concepts such as "flow content"

### ISSUE THREAD

**Issue by annevk** [w3c/mathml-core#195]
I noticed in WebKit that there's functions such as `isFlowContent`, which seems somewhat suspect as HTML only defines those for validation purposes. They're not really meant for implementations (see in particular how `main` is defined therein, for instance).

Is this just something wrong inside WebKit?

**Comment by fred-wang** [comment]
Yes, so I believe I'm the one who implemented this in WebKit, trying to follow what the HTML spec says regarding where MathML elements can be placed inside SVG/HTML elements an vice-versa. Reading again, WebKit tries to prevent creation of renderers when the DOM tree does not follow the HTML constraints:

- `isFlowContent` is only used to determine whether an element inside an `<annotation-xml>` element should create a renderer [1]. Incidentally MathML Core's implementation of `<semantics>`, as currently done in Firefox/Chromium, is much simpler and ignores the encoding attribute.

- Similarly, `isPhrasing` content is only used (besides the implementation of `isFlowContent`) to determine whether an element inside a MathML token element should create a renderer [2].

I believe WebKit can relax these constraints without the risk of breaking existing content, they don't exist in Firefox/Chromium/specs and make implementation more simple. IIRC, WebKit has an internal MathML test for them too.

[1] https://searchfox.org/wubkat/rev/17b431999014409e4831dce71e69e0033d87ede5/Source/WebCore/mathml/MathMLAnnotationElement.cpp#94
[2] https://searchfox.org/wubkat/rev/17b431999014409e4831dce71e69e0033d87ede5/Source/WebCore/mathml/MathMLTokenElement.cpp#80

**Comment by annevk** [comment]
It seems that the requirements on browsers in https://w3c.github.io/mathml-core/#html-and-svg might have led to this. Those requirements are rather vague.

Really user agents need to be able to render arbitrary trees and we shouldn't talk about things that are allowed/conforming. We should talk about how user agents need to render arbitrary trees. (And perhaps if all of MathML box generating is delegated to CSS nothing much needs to be said about it, as it already follows from the DOM and CSS.)

**Comment by annevk** [comment]
If the content isn't helping toward addressing that goal, not saying anything is better.

Lets evaluate:

> When [parsing HTML documents](https://html.spec.whatwg.org/#parsing) user agents must treat any tag name corresponding to a [MathML Core Element](https://w3c.github.io/mathml-core/#dfn-mathml-core-elements) as belonging to the [MathML namespace](https://infra.spec.whatwg.org/#mathml-namespace).

This seems to partially duplicate a requirement from the HTML standard, in particular its parsing section. It seems confusing at best.

> Users agents must allow mixing HTML, SVG and MathML elements as allowed by sections [HTML integration point](https://html.spec.whatwg.org/#html-integration-point), [MathML integration point](https://html.spec.whatwg.org/#mathml-text-integration-point), [tree construction dispatcher](https://html.spec.whatwg.org/#tree-construction-dispatcher), [MathML](https://html.spec.whatwg.org/#mathml) and [SVG](https://html.spec.whatwg.org/#svg-0) from [[HTML](https://w3c.github.io/mathml-core/#bib-html)].

The DOM's node tree concept has allowed this forever and user agents have as well, so this doesn't really add anything. Again, at best confusing.

> When evaluating the SVG [requiredExtensions](https://www.w3.org/TR/SVG/struct.html#RequiredExtensionsAttribute) attribute, user agents must claim support for the language extension identified by the [MathML namespace](https://infra.spec.whatwg.org/#mathml-namespace).

I believe `requiredExtensions` isn't implemented and it seems like a rather bad feature too, so this does not strike me like a good idea.

---

The example seems mostly fine modulo `requiredExtensions`.

---

As for the note:

> The `<math>` element can be used at position permitted for [flow content](https://html.spec.whatwg.org/multipage/dom.html#flow-content-2) (e.g. a [`<foreignObject>`](https://www.w3.org/TR/SVG/embedded.html#ForeignObjectElement) element) or [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2).

This is misleading. It can also be used elsewhere. That goes for the other points as well. Presumably this is talking about what is conforming which might be useful for web developers, but for implementers this doesn't help and goes against your stated goal of helping them deal with this consistently.

What implementers need is clarity on what CSS "boxes" MathML elements end up generating and how those boxes interact with the boxes that already exist. That's all.

**Comment by annevk** [comment]
Sounds good overall. I think converting the note to examples might work. If the audience is implementers I think we should not tie anything to HTML standard conformance concepts as those don't matter for the majority of implementers (they do matter for validators, but that's probably best covered separately).

**Comment by fred-wang** [comment]
Thanks. if the Math WG people are ok I can go ahead and do the changes propopsed in https://github.com/w3c/mathml-core/issues/195#issuecomment-1697133864 then

**Comment by bkardell** [comment]
@fred-wang 

The MathWG today gave that go ahead. Please feel free to do it.
