### ISSUE TITLE
Vertical Alignment of <mo> delimiters

### ISSUE THREAD

**Issue by ronkok** [w3c/mathml-core#205]
I propose two edits to MathML-Core section 3.2.4.3 _Layout of operators_.

The first edit is shown below in **bold**.

2.  If the operator has the `stretchy` property **or has the `minsize` attribute**:

There is a current problem with `<mo>` delimiters in both Chromium and WebKit. This problem affects a parenthesis which does not have `stretchy="true"` but _has_ been up-sized with a `minsize` attribute.  Such delimiters should be vertically aligned to be centered on the math axis. Both Chromium and WebKit fail to make that adjustment.

You can see an example if you navigate to the Temml [Mozilla tests](https://temml.org/tests/mozilla-tests) and scroll down to line 14. There are more examples in the [Wikipedia tests](https://temml.org/tests/wiki-tests), in lines 178 & 179.

I propose a second edit after the line which reads “Otherwise, the `stretch axis` of the operator is block. The following steps are performed.”

I propose to insert item 2 below.

2.  If the size of in-flow children make it unnecessary to shape a stretchy glyph in the block direction, then fallback to the layout algorithm of 3.2.1.1 Layout of `<mtext>`.

This problem also occurs in both Chromium and WebKit. An example can be seen [here](https://temml.org/#%5Cleft(%20x%20%5Cright)). Those parentheses do not need to stretch, and they don’t. So far, so good. The problem is that they do not need an adjustment to their vertical alignment. But the alignment has been changed. They are placed too high.

My first proposal is related to Chromium [Issue 1468676](https://bugs.chromium.org/p/chromium/issues/detail?id=1468676). My second proposal is related to Chromium [Issue 1350167](https://bugs.chromium.org/p/chromium/issues/detail?id=1350167).

**Comment by davidcarlisle** [comment]
I don't think the first edit is needed, as minsize only applies to stretchy operators (which may implicitly have that property via the operator dictionary).

eg 

https://www.w3.org/TR/MathML3/chapter3.html#presm.presatt says

> minsize ... Specifies the minimum size of the operator when stretchy;

https://www.w3.org/TR/mathml-core/#operator-fence-separator-or-accent-mo

> Finally the minsize and maxsize attributes add additional constraints over the stretch size.

**Comment by ronkok** [comment]
> I don't think the first edit is needed, as minsize only applies to stretchy operators …

That’s a reasonable position. My aim was to eliminate ambiguity. If everyone agrees with David’s interpretation of the current specification, then the first edit is superfluous.

**Comment by brucemiller** [comment]
Is the underlying problem with the first chromium issue, that chromium does *not* set `stretchy=true` (from the operator dictionary)?

**Comment by ronkok** [comment]
The delimiters do change size when a `minsize`  attribute has been set. Looking at it from the outside, that's as much as I know. Perhaps some internal switch is not properly flipped.

**Comment by NSoiffer** [comment]
We discussed this at the core meeting today. The feeling was that the problem is that the `symmetric` property isn't being respected.

So I would suggest that @ronkok's proposal be tweaked:

In 3.2.4.3, the second clause should be changed to (change is in bold):
2.  If the operator has the `stretchy` property **or has the `symmetric` property**:

This change means that clause 4 of the "Otherwise" part kicks in and ascent and descent are set correctly:
> 4. If the operator has the <a data-link-type="dfn|abstract-op" data-link-for="embellished operator" data-xref-for="embellished operator" href="#dfn-symmetric" class="internalDFN" id="ref-for-dfn-symmetric-2"><code>symmetric</code></a> property then set the target sizes<code>T<sub>ascent</sub></code> and<code>T<sub>descent</sub></code> to<code>S<sub>ascent</sub></code> and<code>S<sub>descent</sub></code> respectively...

**Comment by fred-wang** [comment]
I haven't checked things in details, but I agree with @davidcarlisle that per MathML full `symmetric`, `maxsize`, `minsize` only have effects when the operator is stretchy per https://w3c.github.io/mathml/spec.html#presm_mo_dict_attrs so I don't think the second clause "If the operator has the stretchy" should be modified to force handling  `symmetric`, `maxsize` or `minsize`.

**Comment by davidcarlisle** [comment]
A related mo alignment issue is shown at
https://w3c.github.io/mathml-docs/intent-examples/#id-1-afbf0c9d54fa697fee15f8c64feda4b2
where chrome sets the ] far too low, I meant to report that at the chromium tracker but haven't done so yet.

firefox
![image](https://github.com/w3c/mathml-core/assets/1268738/d60131ef-2932-480e-8ec3-9cc835f78591)


chrome

![image](https://github.com/w3c/mathml-core/assets/1268738/09b1e533-1087-4605-b3ef-aa0700b9f655)

**Comment by NSoiffer** [comment]
We discussed this again at the meeting today. The feeling is that since the MathML full spec says `stretchy` must be true for `symmetric`, `min`, and `max` attributes to have an effect, we should "stay the course" and not make a change. Making a change has the potential to break existing MathML usage (although we don't know how much, if any, would break). It is always possible to set  `stretchy` and adjust `min` or `max` to prevent stretching the chars, so there is a work-around.

For the record: @dginev mentioned that CSS has a method to set min/max width/height. As noted in the call, this sets the _bounding box_ min/max, not the min/max of a stretchy char. So there is no conflict between these attributes/properties.

@ronkok: we propose to close this issue. Do you object to that?

**Comment by ronkok** [comment]
@NSoiffer, Thank you for the follow-up. I agree completely with a decision to forego the first edit that I suggested in this issue.

But the original post also contains a second suggested edit to MathML-Core section 3.2.4.3: 

>I propose a second edit after the line which reads “Otherwise, the stretch axis of the operator is block. The following steps are performed.”
>
>I propose to insert item 2 below.
>
>If the size of in-flow children make it unnecessary to shape a stretchy glyph in the block direction, then fallback to the layout algorithm of 3.2.1.1 Layout of <mtext>.

That edit is still worthwhile. Its adoption would eliminate a vertical mis-placement of parentheses as shown [here](https://temml.org/#%5Cleft(%20x%20%5Cright)).

I think closing this issue would be premature until that suggestion is at least considered.

Perhaps you think it should be a separate, stand-alone issue. I would be happy to open one if you prefer.

**Comment by NSoiffer** [comment]
I was initially confused by your example because it looked good to me. Then I realized it was because I was viewing it in Firefox. In Chrome, it looks bad as you mentioned:
<table>
<tr>
<td>Chrome:</td><td><img src="https://github.com/w3c/mathml-core/assets/1545836/f1b08d5a-a842-4f59-8b63-09e91a2a9874"></td>
<tr></tr>
<td>Firefox:</td><td> <img src="https://github.com/w3c/mathml-core/assets/1545836/d6bc520d-436e-4932-9303-db1dde9e3277"></td>
</tr>
</table>

This should be part of the next meeting (January due to the holidays). Hopefully some people will chime in your suggested spec change.

**Comment by dginev** [comment]
I have been asked by arXiv to raise awareness of the impact of this issue, cross-referencing https://github.com/arXiv/html_feedback/issues/354#issuecomment-1962385739

**Comment by bkardell** [comment]
The working group discussed this yesterday, minutes follow: 

> BK: Fred suggested that he expects the spec might not need to be updated and that it is just a bug in chromium, but not firm

> DG: the resolution was not to make changes. 
> DG: there are several things that break. It is hard to to know why. It could be the spec or bug. Needs to find a test showing the problem

> DG: I need to read more of  Fred's existing tests. 

> **action**:  DG to find a test he wants to discuss or make one. 

> NS: we can close this issue if a chrome bug  report has been filed.

> **action** BK to identify whether there is a chromium bug for vertical alignment. If there is, close 205, adding a link to the chrome bug.

**Comment by ronkok** [comment]
Chromium [issue #40068339](https://issues.chromium.org/issues/40068339) may have the same root cause.

**Comment by fred-wang** [comment]
This is maybe unrelated to the present discussion, but https://w3c.github.io/mathml-core/#dfn-shape-a-stretchy-glyph takes the target size Tascent + Tdescent as a parameter (since the MATH table only provides advanceMeasurement) and then https://w3c.github.io/mathml-core/#layout-of-operators calculates a Δ to make sure the actual selected glyph and the ideal (Tascent, Tdescent) target would have their vertical centers aligned.

Below is an example, but without debugging more I'm not sure how to interpret the browsers's behavior here. I guess it would be interesting to check what TeX or Microsoft Word do for equivalent setup.


```
<!DOCTYPE html>
<link
 rel="stylesheet"
 href="https://fred-wang.github.io/MathFonts/LatinModern/mathfonts.css" />
<meta charset="UTF-8">
<style>
 math { font-size: 32pt; }
</style>
<math display="block">
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height=".25em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth=".25em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height=".125em" depth=".125em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height=".5em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth=".5em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth=".25em" height=".25em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height=".75em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth=".75em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height=".375em" depth=".375em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height="1em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="1em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth=".5em" height=".5em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height="1.5em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="1.5em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth=".75em" height=".75em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height="2em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="2em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height="1em" depth="1em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height="2.5em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="2.5em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="1.25em" height="1.25em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded height="5em" depth="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="5em" height="0" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
 <mrow>
  <mo symmetric="false">(</mo>
  <mpadded depth="2.5em" height="2.5em" width="5px" style="background: blue"><mn></mn></mpadded>
 </mrow>
</math>
```

**Comment by ronkok** [comment]
I am closing this issue as complete. Chrome Canary now renders these delimiters at the correct vertical alignment.

A big thank you to @fred-wang. I this this is terrific and I have contributed $500 to [MathML-Core-Support](https://opencollective.com/mathml-core-support).

**Comment by fred-wang** [comment]
@ronkok you're welcome and thanks for your donation. I'm tentatively converting your original tests to WPT: https://chromium-review.googlesource.com/c/chromium/src/+/5433295 (I was not able to reproduce with custom web fonts used by MathML wpt tests, so I'm using the default font instead, which might not make the test very robust, but let's see).
