### ISSUE TITLE
MathML-Core Agenda 10/30/2023

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#210]
Status updates

* Publishing [#170](https://github.com/w3c/mathml-core/issues/170) 

* Specify empty `<mo>` treatment [#209](https://github.com/w3c/mathml-core/issues/209)

* Reflowing content inside MathML token elements [#208](https://github.com/w3c/mathml-core/issues/208)

* Vertical Alignment of `<mo>` delimiters [#205](https://github.com/w3c/mathml-core/issues/205)

* Adjusted height & depth of elements moved via voffset [#203](https://github.com/w3c/mathml-core/issues/203)

[Edited -- fixed links]

**Comment by davidcarlisle** [comment]
Reminder: UK/Europe has ended daylight saving time this morning, so the calls will be an hour out until the USA gets back in sync.
