### ISSUE TITLE
MathML-Core March 25, 2024 Agenda

### ISSUE THREAD

**Issue by bkardell** [w3c/mathml-core#226]
I think we are all set for wide review stuff..?

* [Issues for publishing CR draft](https://github.com/w3c/mathml-core/issues/170)

* [Idea: Consider introducing CSS math-leading-space / math-trailing-space properties #218](https://github.com/w3c/mathml-core/issues/218)

* [Alignment of <mo> delimiters](https://github.com/w3c/mathml-core/issues/205)

* [Define Accessibility Mappings for MathML Elements ](https://github.com/w3c/mathml-core/issues/196)

* [Regenerate PNG examples with official chromium build #155
](https://github.com/w3c/mathml-core/issues/155)

* [Applying visual effects](https://github.com/w3c/mathml-core/issues/162)

**Comment by dginev** [comment]
- It would be great to resolve #103 before CR, if possible. 
  - I requested extra time for it last meeting, so maybe upto 5 minutes to finalize discussion? Could be set as the final meeting item to guard time.

**Comment by brucemiller** [comment]
I second @dginev 's comment; And #103 is coupled with https://github.com/w3c/mathml/issues/489.  To help with a decision, does anyone recall the reasoning for the change to interpretation of percent in Core?

As I noted in #103, either choice involves a change to one of the specs, *and* a change to at least one implementation.

**Comment by bkardell** [comment]
We should also add https://github.com/WICG/sanitizer-api/issues/103#issuecomment-2009143357

**Comment by ljmaher** [comment]
Done.


Regards
Louis Maher
Phone: 713-444-7838
Email: ***@***.***

**Comment by bkardell** [comment]
227 should go in next month's agenda
