### ISSUE TITLE
Explain the mapping tables (appendix C)

### ISSUE THREAD

**Issue by bert-github** [w3c/mathml-core#234]
(This is part of the I18n WG review.)

C. Mathematical Alphanumeric Symbols
https://www.w3.org/TR/mathml-core/#new-text-transform-mappings

> The following tables enumerate the mathematical alphanumeric symbols with form bold, italic, fraktur, monospace, double-struck etc that are available in Unicode. For each of them, the character in its normal form is provided as well as the difference between the code points of the transformed and original characters. 

The italic mapping table is used to implement the 'text-transform' property ([section 4.2](https://www.w3.org/TR/mathml-core/#new-text-transform-values)). The other mapping tables are not explained, but appear to implement various values of the mathvariant attribute ([section 3.2.2](https://www.w3.org/TR/mathml-core/#the-mi-element)) that are defined in MathML3, but not in MathML Core (‘bold’, ‘double-struck’, ‘fraktur’, etc.). Some browsers use them that way.

The spec suggests that those MathML3 values must be ignored. If that is the case, why are those tables in the spec? And if browsers are allowed to support those values, shouldn't the role of the tables be explained?

**Comment by fred-wang** [comment]
Except for italic, this is mostly legacy and non-normative stuff from the original mathvariant / text-transform proposal.

This is not implemented in Chromium and is being tentatively removed from Firefox. I believe some legacy WPT tests still use it. Ultimately, we should remove them from MathML Core and probably only have them to web-developer-oriented doc.

**Comment by davidcarlisle** [comment]
@bkardell  @fred-wang  We could remove them all (and for example reference Uniocde or https://w3c.github.io/xml-entities/italic.html for the default italic mapping) or we could leave in the italic table and just delete the rest?

**Comment by bkardell** [comment]
Per the working group today, we agreed that we like @davidcarlisle's solution to this and @NSoiffer will review and get that merged.  This should resolve the issue

**Comment by bert-github** [comment]
The i18n WG agrees, too.
