### ISSUE TITLE
opentype math in harfbuzz

### ISSUE THREAD

**Issue by davidcarlisle** [w3c/mathml-core#242]
@fred-wang  the mathml-core spec references your document

https://frederic-wang.fr/opentype-math-in-harfbuzz.html

except that's 404, do you want to reference a more modern harfbuzz doc or is your original document still available somewhere?

**Comment by bkardell** [comment]
Worst case, there's a historical link from 1 year ago.

https://web.archive.org/web/20230616202703/https://frederic-wang.fr/opentype-math-in-harfbuzz.html

**Comment by fred-wang** [comment]
It's https://frederic-wang.fr/2016/04/16/opentype-math-in-harfbuzz/
