### ISSUE TITLE
MathML Core XML Schema Definition (*.xsd)

### ISSUE THREAD

**Issue by rrrnld** [w3c/mathml-core#262]
I hope this repository's issue tracker is the right place to ask this question, sorry if it isn't: I was searching for an XSD describing the MathML Core schema, but couldn't find one. Does one exist? It would be very helpful for validation.

**Comment by davidcarlisle** [comment]
here is fine, although the schema for all mathml variants are developed together at

https://github.com/w3c/mathml-schema

The primary version is the Relax NG schema the XSD and DTD are generated from that.

Although I have just noticed that the xsd doesn't have mathml-core only (parts of) mathml full.  It looks like it's generated but never got pushed to git, let me check. It may have been that I didn't commit the core one as there was an issue with its generation. I'll ping here when something is available to test

**Comment by davidcarlisle** [comment]
@rrrnld Thanks for this report I fixed the immediate oversight that `mathml4-core.xsd` was being generated but not in git.

It isn't so well tested yet but

```
$ xmllint --noout --schema xsd/mathml4-core.xsd test/test-core-00.xml 
test/test-core-00.xml validates
```

validates one core file and

```
$ xmllint --noout --schema xsd/mathml4-core.xsd test/test-full-01.xml 
test/test-full-01.xml:1: element math: Schemas validity error : Element '{http://www.w3.org/1998/Math/MathML}math', attribute '{http://www.w3.org/XML/1998/namespace}lang': The attribute '{http://www.w3.org/XML/1998/namespace}lang' is not allowed.
test/test-full-01.xml:1: element math: Schemas validity error : Element '{http://www.w3.org/1998/Math/MathML}math', attribute '{http://www.w3.org/XML/1998/namespace}space': The attribute '{http://www.w3.org/XML/1998/namespace}space' is not allowed.
test/test-full-01.xml:1: element math: Schemas validity error : Element '{http://www.w3.org/1998/Math/MathML}math', attribute 'alignmentscope': The attribute 'alignmentscope' is not allowed.
test/test-full-01.xml:3: element mglyph: Schemas validity error : Element '{http://www.w3.org/1998/Math/MathML}mglyph': This element is not expected. Expected is ( {http://www.w3.org/1999/xhtml}* ).
test/test-full-01.xml:5: element apply: Schemas validity error : Element '{http://www.w3.org/1998/Math/MathML}apply': This element is not expected.
test/test-full-01.xml fails to validate
```

correctly flags one mathml4 full file as invalid to mathml core so the schema isn't totally wrong.

The current version is simply an automatic conversion of `mathml4-core.rnc` to XSD syntax with no hand corrections.

specifically

```
java -jar build/trang.jar rnc/mathml4-core.rnc mathml4-core.xsd
```

The conversion of the mathml full schema requires some pre-processing to avoid trang errors in the conversion (see `build/makexsd` script in the mathml-schemas repository), but for mathml-core I think a direct conversion works fine.

https://github.com/w3c/mathml-schema/blob/main/xsd/mathml4-core.xsd

I think I should close this issue as the schema is now available but feel free to open a new one if there are issues with the schema.

**Comment by rrrnld** [comment]
Thank you!
