### ISSUE TITLE
Generate new PNGs for examples in the core spec

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml-core#45]
Many of the examples in the core spec are very poorly rendered. E.g, example-style.png looks like:
![image](https://user-images.githubusercontent.com/1545836/123565285-32e3d380-d771-11eb-8485-7258cfdfa39c.png)

with the summation sign much too small (not big as the text says) and the numerator on the RHS not centered.

**Comment by fred-wang** [comment]
There was a mistake in example-style mentioned in the report: it was using "STIX Two" which does not have any MATH table, instead of "STIX Two Math".

I'll open a new issue for regenerating examples.

**Comment by fred-wang** [comment]
Opened https://github.com/w3c/mathml-core/issues/155
