### ISSUE TITLE
Update core spec text to reflect Unicode 14

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml-core#46]
Unicode 14 will introduce two new math script styles: Roundhand and Chancery. These don't get new code point points but instead use the variant selectors U+FE00 and U+FE01.

The core spec has the following that needs to be updated at some point after Unicode 14 is official.

>NOTE
> Unicode does not distinguish between Chancery and Spencerian style for the Unicode MATHEMATICAL SCRIPT characters. However, some mathematical fonts rely on salt or ssXY properties from [OPEN-FONT-FORMAT] to provide both styles. Page authors may use the font-variant-alternates property with corresponding OpenType font features to access these glyphs.

**Comment by fred-wang** [comment]
@NSoiffer I tweaked the note to mention the new Unicode 14 stuff. Maybe this should be in the MathML 4 Full tracker too...
