### ISSUE TITLE
font enumeration in -core

### ISSUE THREAD

**Issue by samuelweiler** [w3c/mathml-core#47]
I would like to see a clearer statement about whether this spec enables font enumeration.  We're working through removing font enumeration capability in other APIs, to reduce fingerprinting surface, so the phrase "The only font informations that are not exposed by other existing Web APIs ..." is not reassuring in and of itself.

**Comment by fred-wang** [comment]
More info was added in https://w3c.github.io/mathml-core/#privacy-considerations ; not sure if there is anything else to do.

**Comment by davidcarlisle** [comment]
Closed in meeting of 29th Jan as any remaining issue is a css issue. and info added as in previous comment.
