### ISSUE TITLE
Handling of out-of-flow elements

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#74]
cc @mrego

I'm not sure there is a concrete use case to e.g. absolutely position a numerator of a fraction. I think Gecko supports it but WebKit does not.

See https://bugs.webkit.org/show_bug.cgi?id=178865

Original report: https://gitlab.com/mathml/MathMLinHTML5/issues/9

**Comment by fred-wang** [comment]
For now I've tweaked the spec to say it forces float to none on MathML element via the UA sheet, but maybe that's not exactly what we want. I've been experimenting with the following test case: 

    
    <div>
      Lorem ipsum
      <math style="float: left">
        <msqrt>
          <mfrac>
            <mn>1</mn>
            <mn>2</mn>
          </mfrac>
        </msqrt>
      </math>
    </div>

    
    <div>
      <math>
        <mtext>Lorem ipsum</mtext>
        <msqrt style="float: left">
          <mfrac>
            <mn>1</mn>
            <mn>2</mn>
          </mfrac>
        </msqrt>
      </math>
    </div>

    
    <div>
      <math>
        <mtext>Lorem ipsum
          <span style="float: left">\sqrt{\frac{1}{2}}</span>
        </mtext>
      </math>
    </div>

I'm currently getting the following rendering in WebKit, Firefox, Chrome (from top to bottom), which is a bit inconsistent:

![mathml-floats](https://user-images.githubusercontent.com/567455/203514474-32b80824-63cd-4b71-bf2d-a6e336213cae.jpg)

Chrome works as I would expect. WebKit completely drops the floats in MathML. Firefox is not able to place floats in mtext.

I guess it is fine to have a floating `<math>` root (it's placed by the parent layout) or floats in token elements (https://w3c.github.io/mathml-core/#layout-of-mtext relies on block flow). However, we probably want to prevent floats in pure MathML layout since we currently don't define any special behavior for them.

**Comment by fred-wang** [comment]
Another interesting case is floats in `<mtd>`:

    
    <div>
      <math>
        <mtable>
          <mtr>
            <mtd>
              <mtext>Lorem ipsum</mtext>
              <msqrt style="float: left">
                <mfrac>
                  <mn>1</mn>
                  <mn>2</mn>
                </mfrac>
              </msqrt>
            </mtd>
          </mtr>
        </mtable>
      </math>
    </div>

which is not handled by Chrome, causes line break in Firefox and is handled by WebKit.

---

For now I'm leaning towards adjusting computed style of elements with a "display: math" parent to force `float: none`.

**Comment by bfgeek** [comment]
> For now I've tweaked the spec to say it forces float to none on MathML element via the UA sheet, but maybe that's not exactly what we want. I've been experimenting with the following test case:

Yeah likely not exactly what you want as that'll prevent <math> elements form floating. You can likley rely on the spec text from:
https://drafts.csswg.org/css-flexbox-1/#flex-containers

E.g. something like "Math containers are not block containers, etc etc etc"

**Comment by fred-wang** [comment]
@bfgeek Thanks. I think this was the spirit of the previous formulation, but it seems a bit unprecise. I was thinking about adjusted computed style to be 'none'. https://w3c.github.io/csswg-drafts/css2/#float-position seems to say something similar for absolutely positioned elements and all browsers interpret that has computing the style to none.

**Comment by fred-wang** [comment]
I've prepared tests for out-of-flow elements in Chromium:
https://chromium-review.googlesource.com/c/chromium/src/+/4056220
https://chromium-review.googlesource.com/c/chromium/src/+/4055563

For now, the choice I made for float is to adjust the computed value to none in 'math' display types, so that MathML-specific layout does not need to deal with them. This is doing a bit more than what is stated in the flexbox/grid specifications which only mention that they don't create floating children. It seems WebKit interpreted the latter as adjusting the computed value of float to none, while Firefox/Chome just ignore the float property. I've opened https://github.com/w3c/csswg-drafts/issues/8130 ; we can likely revise what do for display: math depending on the decision in the CSSWG.

Regarding, absolutely/fixed positioned element, the containing block is defined in https://w3c.github.io/csswg-drafts/css2/#containing-block-details ; Chrome is already able to place absolutely/fixed positioned element in MathML layout using that containing block as a reference point, so I only needed to write the tests accordingly.

Probably MathML Core can be a bit more precise in https://w3c.github.io/mathml-core/#layout-algorithms in "Layout and positioning of out-of-flow child boxes." mentioning the case of floats and referring to CSS2 for the containing block of absolutely/fixed positioned elements.

**Comment by fred-wang** [comment]
I believe this bug is resolved. The spec has been aligned on Chromium's behavior and tests added accordingly.

## Floats

[Similar wording as flex/grid is used](https://w3c.github.io/mathml-core/#css-styling): "The float property does not create floating of elements whose parent's computed display value is block math or inline math, and does not take them out-of-flow."

[Tests were added](https://chromium-review.googlesource.com/c/chromium/src/+/4055563) to check that:

- float property is ignored within elements defaulting to display: math (including token elements)
- float works within a display: block MathML element
- float applies to the <math> element

## Other out-of-flow elements

The [general layout algorithm](https://w3c.github.io/mathml-core/#layout-algorithms) now refers to CSS Position 3 for absolutely-positioned and fixed-positioned: "Layout and positioning of absolutely-positioned and fixed-positioned boxes, as described in [CSS-POSITION-3]. "

[Tests were added](https://chromium-review.googlesource.com/c/chromium/src/+/4056220) to verify

- visual rendering of absolutely positioned mtext elements.
- visual rendering of fixed positioned mtext elements.
- coordinates of absolutely/fixed positioned node for all MathML elements.
