### ISSUE TITLE
Automatically generated tables

### ISSUE THREAD

**Issue by innovimax** [w3c/mathml-core#96]
Operators_2_ascii_chars contains elements at the end of the list that are not 2 ascii chars (it's one character each, non ascii '⧏̸', '⧐̸' )

**Comment by davidcarlisle** [comment]
Yes thanks I'll leave this open for review. I think probably they should be dropped from there and handled  by the general rule for handling U+0338  combinations.

**Comment by davidcarlisle** [comment]
This was just in opdict branch and fixed with update in xml-entities, combinations with the combining slash should not have their own operator dictionary entry, covered by the general rule that the negated character is spaced like the base character.
