### ISSUE TITLE
If T = 0 then set Tascent and Tdescent to minsize/2

### ISSUE THREAD

**Issue by fred-wang** [w3c/mathml-core#97]
For consistency with the rest of the text, this should be
Set Tascent to minsize/2 and Tdescent to Tascent - minsize/2

**Comment by fred-wang** [comment]
if wonder if we should even do if T <= 0 to be safe with weird edge cases.

**Comment by davidcarlisle** [comment]
@fred-wang can you clarify the proposed change?

if Tascent is minsize/2  then your suggested change of Tascent - minsize/2 would set Tdescent to 0 wouldn't it?

or did you mean minsize - minsize/2  (which is same as now apart from numerical accuracy)

**Comment by fred-wang** [comment]
Sorry, I meant:

"Set Tascent to minsize / 2 and then set Tdescent to minsize - Tascent."

which is same as now apart from numerical accuracy and is consistent with the rest of the text.

**Comment by davidcarlisle** [comment]
Ah OK I figured out that was what you must have meant:-)  seems good (and applying it for T negative can't hurt I think).

**Comment by fred-wang** [comment]
Also, while we are here there is a "then then" the line above.

**Comment by davidcarlisle** [comment]
@fred-wang I adjusted the expression and deleted a then
